name: one_page_two_scrolls
description: An example how to use nested scroll view, if you need complex page with two scrolls.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  extended_sliver: ^2.1.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dart_code_metrics: ^5.7.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
